site_name: AdonisFX

theme:
  name: readthedocs
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - content.tooltips
  language: en
  # logo: images/adn_logo_default_2x.png
  # favicon: images/adn_logo_default_2x.png
  palette:
    scheme: slate
    primary: light blue
    accent: deep purple
extra_css:
  - /stylesheets/extra.css
use_directory_urls: false

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/inbibo-ltd/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@inbibo9227/featured
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/people/Inbibo/100064064923495/
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "75%"
        
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2024 <a href="https://www.inbibo.co.uk/"  target="_blank" rel="noopener">Inbibo LTD</a>

# Page tree
nav:
  - Introduction: index.md
  - Terminology: terminology.md
  - Installation: installation.md
  - Licensing: licensing.md
  - Requirements: requirements.md
  - FAQ: faq.md
  - Release Notes: release_notes.md
  - Maya:
    - Index                       : maya/index.md
    - UI Overview                 : maya/ui_overview.md
    - A Simple Setup              : maya/simple_setup.md
    - Deformers:
      - AdnMuscle                 : maya/deformers/muscle.md
      - AdnRibbonMuscle           : maya/deformers/ribbon.md
      - AdnFat                    : maya/deformers/fat.md
      - AdnSkin                   : maya/deformers/skin.md
      - AdnRelax                  : maya/deformers/relax.md
      - AdnSkinMerge              : maya/deformers/skin_merge.md
      - AdnSimshape               : maya/deformers/simshape.md
    - Nodes:
      - Locators                  : maya/nodes/locators.md
      - Sensors                   : maya/nodes/sensors.md
      - AdnActivation             : maya/nodes/activation.md
      - AdnEdgeEvaluator          : maya/nodes/edge_evaluator.md
      - AdnGlue                   : maya/nodes/glue.md
    - Tools:
      - Paint Tool                : maya/tools/paint_tool.md
      - Sensors Connection Editor : maya/tools/sensors_connection_editor.md
      - Mirror                    : maya/tools/mirror_tool.md
      - Export                    : maya/tools/exporter.md
      - Import                    : maya/tools/importer.md
    - Scripts:
      - Mirror                    : maya/scripts/mirror.md
      - I/O                       : maya/scripts/io.md
    - API                         : maya/api.md
